# Generated by Django 5.1.5 on 2025-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerinputquestion',
            name='mark',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('2O', '20'), ('25', '25'), ('30', '30')], max_length=2),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='mark',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('2O', '20'), ('25', '25'), ('30', '30')], max_length=2),
        ),
    ]
