# Generated by Django 5.1.2 on 2025-02-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_room_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_set', to='app.quiz'),
        ),
    ]
