# Generated by Django 5.1.5 on 2025-02-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_integerinputquestion_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerinputquestion',
            name='time',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('2O', '20'), ('25', '25'), ('30', '30')], max_length=2),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='time',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('2O', '20'), ('25', '25'), ('30', '30')], max_length=2),
        ),
    ]
