# Generated by Django 5.1.5 on 2025-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_integerinputquestion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerinputquestion',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
