# Generated by Django 5.0 on 2025-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, quiz will be visible to all tutors'),
        ),
    ]
