# Generated by Django 5.1.2 on 2025-02-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integerinputquestion',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='truefalsequestion',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='integerinputquestion',
            name='number',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='number',
        ),
        migrations.AddField(
            model_name='integerinputquestion',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='mark',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='time',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='mark',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='time',
            field=models.IntegerField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='DecimalInputQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, max_length=2)),
                ('mark', models.IntegerField(blank=True, max_length=2)),
                ('correct_answer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decimal_questions', to='app.quiz')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, max_length=2)),
                ('mark', models.IntegerField(blank=True, max_length=2)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='app.quiz')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericalRangeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, max_length=2)),
                ('mark', models.IntegerField(blank=True, max_length=2)),
                ('min_value', models.DecimalField(decimal_places=10, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=10, max_digits=10)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerical_range_questions', to='app.quiz')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, max_length=2)),
                ('mark', models.IntegerField(blank=True, max_length=2)),
                ('items', models.TextField()),
                ('correct_order', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_questions', to='app.quiz')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextInputQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, max_length=2)),
                ('mark', models.IntegerField(blank=True, max_length=2)),
                ('correct_answer', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_questions', to='app.quiz')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
