# Generated by Django 5.0 on 2025-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_img',
            field=models.ImageField(blank=True, default='quiz_images/default_quiz.png', null=True, upload_to='quiz_images/'),
        ),
    ]
