# Generated by Django 5.1.2 on 2025-03-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortingquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='sortingquestion',
            name='items',
        ),
        migrations.AddField(
            model_name='sortingquestion',
            name='options',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
