# Generated by Django 5.1.2 on 2025-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalinputquestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='numericalrangequestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='textinputquestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
    ]
