# Generated by Django 5.1.2 on 2025-03-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_current_question_index_room_is_quiz_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalinputquestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='numericalrangequestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='textinputquestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
