# Generated by Django 5.1.2 on 2025-03-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classroominvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroominvitation',
            unique_together={('classroom', 'student')},
        ),
    ]
