# Generated by Django 5.1.2 on 2025-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_decimalinputquestion_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalrangeresponse',
            name='answer',
            field=models.FloatField(),
        ),
    ]
