# Generated by Django 5.1.2 on 2025-02-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_decimalinputquestion_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalinputquestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='decimalinputquestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numericalrangequestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numericalrangequestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='textinputquestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='textinputquestion',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='time',
            field=models.IntegerField(),
        ),
    ]
