# Generated by Django 5.1.2 on 2025-03-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_classroominvitation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together={('classroom', 'student')},
        ),
    ]
