# Generated by Django 5.1.2 on 2025-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_decimalinputquestion_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalinputquestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='integerinputquestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='numericalrangequestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sortingquestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='textinputquestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
