# Generated by Django 5.1.2 on 2025-02-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_roomparticipant_score'),
        ('app', '0005_alter_decimalinputquestion_time_and_more'),
    ]

    operations = [
    ]
