# Generated by Django 5.1.2 on 2025-02-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classroominvitation'),
        ('app', '0006_integerinputresponse_truefalseresponse'),
        ('app', '0007_quizstate'),
    ]

    operations = [
    ]
