# Generated by Django 5.0 on 2025-03-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_classroomstudent_unique_together'),
        ('app', '0008_merge_20250228_1225'),
    ]

    operations = [
    ]
