# Generated by Django 5.0 on 2025-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20250228_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(blank=True, choices=[('L', 'Live'), ('R', 'Releasable')], max_length=1),
        ),
    ]
