# Generated by Django 5.0 on 2025-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='decimalinputquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='integerinputquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='numericalrangequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='sortingquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='textinputquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
        migrations.AddField(
            model_name='truefalsequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
    ]
