# Generated by Django 5.0 on 2025-03-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250303_1335'),
        ('app', '0009_merge_20250303_1423'),
    ]

    operations = [
    ]
