# Generated by Django 5.0 on 2025-03-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250303_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='The Classroom associated with this room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_rooms', to='app.classroom'),
        ),
    ]
