# Generated by Django 5.1.2 on 2025-03-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_decimalinputquestion_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroominvitation',
            unique_together={('classroom', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together={('classroom', 'student')},
        ),
    ]
